spring:
    redis:
        host: 121.4.218.176
        port: 6379
        timeout: 10000
        jedis:
            pool:
                max-active: 8
                max-wait: -1
                max-idle: 8
                min-idle: 0
        password: ssAxy521!@#
