spring:
    application:
        name: two
    #默认用集群配置，3主3从共6节点的集群
    cluster:
        host: 192.168.111.144
        cluster:
            nodes:
                - 192.168.111.144:7000
                - 192.168.111.144:7001
                - 192.168.111.144:7002
                - 192.168.111.144:7003
                - 192.168.111.144:7004
                - 192.168.111.144:7005
            max-redirects: 2
        lettuce:
            pool:
                max-active: 1000
                max-idle: 10
                min-idle: 3
                max-wait: -1
    single:
        timeout: 6000ms
        database: 0
        host: 192.168.111.144
        password:
        port: 6379
        jedis:
            pool:
                max-active: 1000
                max-idle: 10
                min-idle: 3
                max-wait: -1
    lettuce:
        timeout: 6000ms
        database: 0
        host: 192.168.111.144
        port: 6379
        lettuce:
            pool:
                max-active: 1000
                max-idle: 10
                min-idle: 3
                max-wait: -1
    sentinel:
        timeout: 6000ms
        database: 0
        host: 192.168.111.144
        port: 6379
        lettuce:
            pool:
                max-active: 1000
                max-idle: 10
                min-idle: 3
                max-wait: -1
        sentinel:
            master: mymaster
            nodes:
                - 192.168.111.144:26379
                - 192.168.111.144:26380
                - 192.168.111.144:26381